import sys
import os

# Add project root to path so pipeline/ and src/ are importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import streamlit as st
from pipeline.stage_05_prediction import PredictionPipeline

# ------------------------------------------------------------------ #
# Page config                                                          #
# ------------------------------------------------------------------ #
st.set_page_config(
    page_title="Dialogue Summarizer",
    page_icon="📝",
    layout="centered",
)

# ------------------------------------------------------------------ #
# Load model once and cache it                                         #
# ------------------------------------------------------------------ #
@st.cache_resource(show_spinner="Loading summarization model...")
def load_pipeline():
    import os
    token = os.environ.get("HF_TOKEN")
    if token:
        from huggingface_hub import login
        login(token=token)
    return PredictionPipeline(hub_model_id="Aaditya-Nanda/pegasus-samsum")

pipeline = load_pipeline()

# ------------------------------------------------------------------ #
# UI                                                                   #
# ------------------------------------------------------------------ #
st.title("📝 Dialogue Summarizer")
st.markdown(
    "Paste a conversation below and get an **abstractive summary** "
    "generated by a fine-tuned **Pegasus** model."
)

st.divider()

# Sample dialogue button
SAMPLE = """Hannah: Hey, are you free this weekend?
Amanda: Yes! What's up?
Hannah: A few of us are going hiking on Saturday. Want to join?
Amanda: That sounds amazing, I'd love to!
Hannah: Great, we're meeting at the trailhead at 9am.
Amanda: Perfect, I'll be there. Should I bring anything?
Hannah: Just water, snacks, and good shoes. We'll be back by noon.
Amanda: Awesome, can't wait!"""

if st.button("Load sample dialogue"):
    st.session_state["dialogue"] = SAMPLE

dialogue = st.text_area(
    label="Paste your dialogue here:",
    value=st.session_state.get("dialogue", ""),
    height=250,
    placeholder="Hannah: Hey, are you free this weekend?\nAmanda: Yes! ...",
)

col1, col2 = st.columns([1, 4])
with col1:
    summarize = st.button("Summarize", type="primary", use_container_width=True)
with col2:
    clear = st.button("Clear", use_container_width=True)

if clear:
    st.session_state["dialogue"] = ""
    st.rerun()

if summarize:
    if not dialogue.strip():
        st.warning("Please paste a dialogue before clicking Summarize.")
    else:
        with st.spinner("Generating summary..."):
            summary = pipeline.predict(dialogue)
        st.divider()
        st.subheader("Generated Summary")
        st.success(summary)

        # Word count stats
        dialogue_words = len(dialogue.split())
        summary_words = len(summary.split())
        ratio = round(dialogue_words / max(summary_words, 1), 1)

        c1, c2, c3 = st.columns(3)
        c1.metric("Dialogue words", dialogue_words)
        c2.metric("Summary words", summary_words)
        c3.metric("Compression ratio", f"{ratio}x")

# ------------------------------------------------------------------ #
# Footer                                                               #
# ------------------------------------------------------------------ #
st.divider()
st.caption(
    "Model: google/pegasus-xsum fine-tuned on DialogSum | "
    "Built with HuggingFace Transformers + Streamlit"
)