import os
import sys
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"

# Add project root to path so pipeline/ and src/ are importable.
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(SRC_DIR))

# Avoid Streamlit's file watcher scanning large dependency trees on Cloud.
os.environ.setdefault("STREAMLIT_SERVER_FILE_WATCHER_TYPE", "none")

import streamlit as st

PRIMARY_MODEL_ID = "Aaditya-Nanda/pegasus-samsum"
LIGHTWEIGHT_FALLBACK_MODEL_ID = "sshleifer/distilbart-xsum-12-6"
FALLBACK_MODEL_ID = "google/pegasus-xsum"

# ------------------------------------------------------------------ #
# Page config                                                          #
# ------------------------------------------------------------------ #
st.set_page_config(
    page_title="Dialogue Summarizer",
    page_icon="📝",
    layout="centered",
)

# ------------------------------------------------------------------ #
# Load model once and cache it                                         #
# ------------------------------------------------------------------ #
@st.cache_resource(show_spinner=True)
def load_pipeline():
    import os
    from pipeline.stage_05_prediction import PredictionPipeline

    token = os.environ.get("HF_TOKEN")
    if token:
        from huggingface_hub import login

        login(token=token)

    model_candidates = [
        PRIMARY_MODEL_ID,
        LIGHTWEIGHT_FALLBACK_MODEL_ID,
        FALLBACK_MODEL_ID,
    ]
    last_error = None
    for model_id in model_candidates:
        try:
            pipeline = PredictionPipeline(hub_model_id=model_id)
            return pipeline, model_id
        except Exception as exc:
            last_error = exc

    raise RuntimeError("Unable to load any summarization model.") from last_error

# ------------------------------------------------------------------ #
# UI                                                                   #
# ------------------------------------------------------------------ #
st.title("📝 Dialogue Summarizer")
st.markdown(
    "Paste a conversation below and get an **abstractive summary** "
    "generated by a fine-tuned **Pegasus** model."
)

st.divider()

# Sample dialogue button
SAMPLE = """Hannah: Hey, are you free this weekend?
Amanda: Yes! What's up?
Hannah: A few of us are going hiking on Saturday. Want to join?
Amanda: That sounds amazing, I'd love to!
Hannah: Great, we're meeting at the trailhead at 9am.
Amanda: Perfect, I'll be there. Should I bring anything?
Hannah: Just water, snacks, and good shoes. We'll be back by noon.
Amanda: Awesome, can't wait!"""

if st.button("Load sample dialogue"):
    st.session_state["dialogue"] = SAMPLE

dialogue = st.text_area(
    label="Paste your dialogue here:",
    value=st.session_state.get("dialogue", ""),
    height=250,
    placeholder="Hannah: Hey, are you free this weekend?\nAmanda: Yes! ...",
)

col1, col2 = st.columns([1, 4])
with col1:
    summarize = st.button("Summarize", type="primary", use_container_width=True)
with col2:
    clear = st.button("Clear", use_container_width=True)

if clear:
    st.session_state["dialogue"] = ""
    st.rerun()

if summarize:
    if not dialogue.strip():
        st.warning("Please paste a dialogue before clicking Summarize.")
    else:
        try:
            with st.spinner("Generating summary..."):
                pipeline, loaded_model_id = load_pipeline()
                summary = pipeline.predict(dialogue)
            st.divider()
            st.subheader("Generated Summary")
            st.success(summary)
            if loaded_model_id != PRIMARY_MODEL_ID:
                st.info(
                    "Fine-tuned model is unavailable right now, so the app used "
                    f"`{loaded_model_id}` instead."
                )

            # Word count stats
            dialogue_words = len(dialogue.split())
            summary_words = len(summary.split())
            ratio = round(dialogue_words / max(summary_words, 1), 1)

            c1, c2, c3 = st.columns(3)
            c1.metric("Dialogue words", dialogue_words)
            c2.metric("Summary words", summary_words)
            c3.metric("Compression ratio", f"{ratio}x")
        except Exception as exc:
            st.error(
                "The summarization model could not be loaded on this deployment. "
                "Please try again in a moment."
            )
            st.exception(exc)

# ------------------------------------------------------------------ #
# Footer                                                               #
# ------------------------------------------------------------------ #
st.divider()
st.caption(
    "Model: google/pegasus-xsum fine-tuned on DialogSum | "
    "Built with HuggingFace Transformers + Streamlit"
)
